general.live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Iosevka Term Nerd Font"

[font.glyph_offset]
x = 2
y = 2

[font.offset]
x = 0
y = 3

[scrolling]
history = 100000

[window]
decorations = "buttonless"
dynamic_padding = false
dynamic_title = true
opacity = 1

[window.padding]
x = 5
y = 5
